# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-27 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFeatureGroupMap',
            new_name='ProductFeatureGroup',
        ),
        migrations.RenameModel(
            old_name='ProductOrgMap',
            new_name='ProductOrg',
        ),
    ]
