# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-28 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_auto_20180928_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='soft_delete',
            field=models.BooleanField(default=False, verbose_name='soft delete'),
        ),
        migrations.AddField(
            model_name='product',
            name='soft_delete',
            field=models.BooleanField(default=False, verbose_name='soft delete'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='soft_delete',
            field=models.BooleanField(default=False, verbose_name='soft delete'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='soft_delete',
            field=models.BooleanField(default=False, verbose_name='soft delete'),
        ),
        migrations.AddField(
            model_name='tokenvalidation',
            name='soft_delete',
            field=models.BooleanField(default=False, verbose_name='soft delete'),
        ),
        migrations.AddField(
            model_name='user',
            name='soft_delete',
            field=models.BooleanField(default=False, verbose_name='soft delete'),
        ),
    ]
