# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-28 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_auto_20180928_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeaturegroup',
            name='is_permission',
        ),
    ]
